### ISSUE TITLE
[meta] v0.11.0 Review configuration, content and general user "UI"

### ISSUE THREAD

**Issue by stp-ip** [okkur/syna#94]
Before the final release of v0.11.0 configuration and content needs to be reviewed.

Implementation:
* [x] snake_case preferred #61 
* [x] nested > flat #69 
* [x] descriptive names (at least on the user side)
* [x] fragment specific config only in fragment front-matter
* [x] fragment specific css/js only in called in fragment
* [x]  most minimal config for config.toml
* [x] most minimal front-matter config for fragments
* [x] image resource fallthrough (currently implemented for hero logo only) #124
* [x] makefile for dev pipeline #127

Documentation
* [x] image resource fallthrough #128
* [x] everything is a fragment #125
* [x] current menu configuration #126
* [x] dev stack aka webpack and contribution guideline
